ALTER TABLE INVENTORIES DROP CONSTRAINT FK_INVENTORIES_WAREHOUSES;

ALTER TABLE INVENTORIES DROP CONSTRAINT PK_INVENTORIES;
ALTER TABLE WAREHOUSES DROP PRIMARY KEY;

ALTER TABLE WAREHOUSES ADD WAREHOUSE_ID_NEW VARCHAR2(50);
ALTER TABLE INVENTORIES ADD WAREHOUSE_ID_NEW VARCHAR2(50);

UPDATE WAREHOUSES
SET WAREHOUSE_ID_NEW = TO_CHAR(WAREHOUSE_ID);

UPDATE INVENTORIES I
SET WAREHOUSE_ID_NEW = (
    SELECT W.WAREHOUSE_ID_NEW
    FROM WAREHOUSES W
    WHERE W.WAREHOUSE_ID = I.WAREHOUSE_ID
);

ALTER TABLE WAREHOUSES MODIFY WAREHOUSE_ID_NEW VARCHAR2(50) NOT NULL;
ALTER TABLE INVENTORIES MODIFY WAREHOUSE_ID_NEW VARCHAR2(50) NOT NULL;

ALTER TABLE INVENTORIES DROP COLUMN WAREHOUSE_ID;
ALTER TABLE WAREHOUSES DROP COLUMN WAREHOUSE_ID;

ALTER TABLE WAREHOUSES RENAME COLUMN WAREHOUSE_ID_NEW TO WAREHOUSE_ID;
ALTER TABLE INVENTORIES RENAME COLUMN WAREHOUSE_ID_NEW TO WAREHOUSE_ID;

ALTER TABLE WAREHOUSES
ADD CONSTRAINT PK_WAREHOUSES PRIMARY KEY (WAREHOUSE_ID);

ALTER TABLE INVENTORIES
ADD CONSTRAINT PK_INVENTORIES PRIMARY KEY (PRODUCT_ID, WAREHOUSE_ID);

ALTER TABLE INVENTORIES
ADD CONSTRAINT FK_INVENTORIES_WAREHOUSES
FOREIGN KEY (WAREHOUSE_ID)
REFERENCES WAREHOUSES (WAREHOUSE_ID)
ON DELETE CASCADE;
