spring.application.name=shoppingmall
server.port=8080

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XEPDB1
spring.datasource.username=system
spring.datasource.password=kitri

mybatis.mapper-locations=classpath*:com/company/shoppingmall/mapper/*Mapper.xml
mybatis.type-aliases-package=com.company.shoppingmall.dto
mybatis.configuration.map-underscore-to-camel-case=true

nexacro.front.path=C:/nexacroTest/shoppingmall/frontend/shoppingmallFront/
